#!/usr/bin/env bash

. ~/dotfiles/osx/trackpad.sh
. ~/dotfiles/osx/dock.sh
. ~/dotfiles/osx/finder.sh
#source ~/dotfiles/osx/terminal

sudo nvram SystemAudioVolume=" "

# TODO:
# VLC - fullscreen on startup