# Symlinked to ~/.zshrc

# Reads sources files immediately

source ~/dotfiles/system/env
source ~/dotfiles/system/alias
#source ~/dotfiles/system/prompt

# for ZSH
source ~/dotfiles/system/zshprompt
eval "$(rbenv init -)"

# Rupa Z
if command -v brew >/dev/null 2>&1; then
    # Load rupa's z if installed
    [ -f $(brew --prefix)/etc/profile.d/z.sh ] && source $(brew --prefix)/etc/profile.d/z.sh
fi
eval "$(rbenv init -)"
